name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
      working-directory: ./front-end

    - name: Build project
      run: |
        npm run build
      working-directory: ./front-end

  backend:
    name: Backend Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
      working-directory: ./back-end

    - name: Start backend
      run: |
        npm start
      working-directory: ./back-end
